// app/layout.tsx
import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import localFont from "next/font/local";
import { Providers } from "./providers";
import "./globals.css";
import { AuthProvider } from './Context/AuthContext';


const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
  weight: ["700", "800", "900"],
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Facial Rec",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}

